#!/usr/bin/env python3
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]


def safe_name(text: str) -> str:
    text = re.sub(r"[^a-zA-Z0-9]+", "-", text.lower()).strip("-")
    return (text[:80] or "a1os-product")


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    request = " ".join(sys.argv[1:]).strip()

    if not request:
        print("ERROR: implementation request required", file=sys.stderr)
        return 2

    name = safe_name(request)
    workspace = ROOT / "factory_runs" / name
    artifacts = workspace / "build_artifacts"

    if artifacts.exists():
        # Never silently overwrite an existing generated product.
        i = 2
        while (ROOT / "factory_runs" / f"{name}-{i}").exists():
            i += 1
        workspace = ROOT / "factory_runs" / f"{name}-{i}"
        artifacts = workspace / "build_artifacts"

    files = {
        "README.md": f"""# {name}

Generated by A1OS Factory.

## Product request

{request}

## Status

Implementation scaffold generated successfully.

## Components

- Application workspace
- Docker runtime
- Docker Compose
- CI/CD workflow
- Kubernetes manifests
- Terraform infrastructure scaffold
- Ansible configuration scaffold

## Deployment

No production deployment was performed by this build.
""",

        "app/README.md": f"""# Application

Product: {name}

Request:

{request}

This directory is the application implementation boundary.
""",

        "Dockerfile": """FROM python:3.14-slim

WORKDIR /app

COPY app/ /app/

CMD ["python3", "-c", "print('A1OS product container ready')"]
""",

        "docker-compose.yml": f"""services:
  {name}:
    build: .
    container_name: {name}
    restart: unless-stopped
""",

        ".github/workflows/ci.yml": """name: CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate generated product
        run: |
          test -f README.md
          test -f Dockerfile
          test -f docker-compose.yml
          test -f k8s/deployment.yaml
          test -f terraform/main.tf
          test -f ansible/site.yml
""",

        "k8s/deployment.yaml": f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
        - name: {name}
          image: {name}:latest
          imagePullPolicy: IfNotPresent
""",

        "k8s/service.yaml": f"""apiVersion: v1
kind: Service
metadata:
  name: {name}
spec:
  selector:
    app: {name}
  ports:
    - port: 80
      targetPort: 8000
""",

        "terraform/main.tf": f"""terraform {{
  required_version = ">= 1.5"
}}

variable "product_name" {{
  type    = string
  default = "{name}"
}}

output "product_name" {{
  value = var.product_name
}}
""",

        "ansible/site.yml": f"""- name: Configure {name}
  hosts: all
  gather_facts: true
  tasks:
    - name: Report product
      ansible.builtin.debug:
        msg: "Configuring {name}"
""",

        "product.json": json.dumps({
            "product": name,
            "request": request,
            "generated_by": "A1OS Factory",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "deployment_performed": False,
            "status": "generated"
        }, indent=2) + "\n",
    }

    for relative, content in files.items():
        write(artifacts / relative, content)

    manifest = {
        "product": name,
        "request": request,
        "artifact_root": str(artifacts),
        "files": sorted(files),
        "file_count": len(files),
        "deployment_performed": False,
        "status": "verified",
    }

    write(artifacts / "build-manifest.json",
          json.dumps(manifest, indent=2) + "\n")

    required = list(files) + ["build-manifest.json"]
    missing = [f for f in required if not (artifacts / f).is_file()]

    if missing:
        print(json.dumps({
            "status": "failed",
            "product": name,
            "missing": missing,
        }, indent=2), file=sys.stderr)
        return 1

    print("=" * 70)
    print("A1OS FACTORY REAL BUILD EXECUTOR")
    print("=" * 70)
    print(f"Product: {name}")
    print(f"Request: {request}")
    print()
    print("Generated:")
    for f in required:
        print(f" ✓ {f}")
    print()
    print(f"Workspace: {workspace}")
    print(f"Artifacts: {artifacts}")
    print(f"Files: {len(required)}")
    print("Deployment: NOT PERFORMED")
    print("Verification: PASS")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
