const programmes=[["Playgroup & Early Years","18 months – 3 years","Practical life, movement, language, sensory exploration and secure routines."],["Montessori Nursery","3 – 5 years","Hands-on activity, choice, repetition and a prepared learning environment."],["Kindergarten","5 – 6 years","Literacy, numeracy, culture, creativity, independence and school readiness."],["Full-Day Daycare","Early years","Care, play, rest, routines and meaningful early learning throughout the day."]];
const areas=["Practical Life","Sensorial Exploration","Language & Early Literacy","Mathematics & Numeracy","Culture, Nature & Discovery","Creative Arts","Movement & Outdoor Play","Social & Emotional Development"];

export default function Home(){return <main>
<nav className="nav"><a className="brand" href="#home"><b>LO</b><span>Little Oaks<small>Montessori Nursery & Kindergarten</small></span></a><div className="navlinks"><a href="#programmes">Programmes</a><a href="#learning">Learning</a><a href="#contact">Contact</a></div><a className="button" href="#contact">Enquire</a></nav>
<section className="hero" id="home"><div><p className="eyebrow">NURTURE · EXPLORE · GROW</p><h1>A beautiful beginning <em>for little minds.</em></h1><p className="lead">Little Oaks is an early childhood environment where children are cared for, encouraged to explore and supported as they grow in independence, confidence and love of learning.</p><div className="actions"><a className="button primary" href="#contact">Talk to Little Oaks</a><a className="button ghost" href="#programmes">Explore programmes</a></div><div className="facts"><span><b>18 mo – 6 yrs</b>Early childhood</span><span><b>Montessori-inspired</b>Hands-on learning</span><span><b>Mbarara</b>Nyamitanga</span></div></div><aside className="hero-card"><p>THE LITTLE OAKS WAY</p><h2>Small hands.<br/>Big discoveries.</h2><span>Children learn by doing — touching, moving, choosing, repeating, asking questions and discovering the world around them.</span></aside></section>
<section className="intro"><div><p className="eyebrow">WELCOME TO LITTLE OAKS</p><h2>More than childcare.<br/>A foundation for life.</h2></div><p>The early years are when children develop the foundations for how they think, communicate, relate to others and approach new experiences. Little Oaks combines nurturing care with Montessori-inspired early learning.</p></section>
<section className="section" id="programmes"><p className="eyebrow">OUR PROGRAMMES</p><h2>A place to belong,<br/>learn and grow.</h2><div className="cards">{programmes.map(([title,age,text])=><article key={title}><small>{age}</small><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="learning" id="learning"><div><p className="eyebrow">THE MONTESSORI APPROACH</p><h2>Learning begins with curiosity.</h2><p>A prepared environment gives children meaningful opportunities to work with their hands, make choices, practise skills and develop concentration.</p></div><div className="areas">{areas.map((a,i)=><div key={a}><span>{String(i+1).padStart(2,"0")}</span><b>{a}</b></div>)}</div></section>
<section className="promise"><p className="eyebrow">OUR PROMISE</p><h2>Every child deserves to be known.</h2><p>We believe children flourish when they feel safe, respected, understood and trusted to try.</p></section>
<section className="contact" id="contact"><div><p className="eyebrow">COME AND MEET US</p><h2>Let's start your child's<br/>Little Oaks journey.</h2><p>Parents and guardians can contact Little Oaks to discuss programmes, availability, visits and enrolment.</p></div><div className="contact-card"><span>LOCATION</span><b>Nyamitanga, Mbarara</b><p>Along Isingiro Road, Uganda</p><span>ENROLMENT</span><p>Enquiries and admissions information will be provided through the school's official contact channels.</p></div></section>
<footer><b>Little Oaks Montessori Kindergarten & Day Care Centre (U) Limited</b><span>Nyamitanga, Mbarara · Uganda</span><span>© {new Date().getFullYear()} Little Oaks</span></footer>
</main>}
