import asyncio
import inspect
import json
import sys

sys.path.insert(0, ".")

from core.state import A1OS


TARGET = "digital_world_recovery"
ACTION = "repair"
ENTITY = "primary-device"


async def verify():
    system = A1OS()
    registry = system.capabilities

    results = []

    def record(name, passed, **extra):
        results.append({
            "name": name,
            "passed": passed,
            **extra,
        })

    # 1. The capability must actually be registered.
    registered = TARGET in registry.list()
    record(
        "target_capability_is_registered",
        registered,
        capability=TARGET,
    )

    if not registered:
        return {
            "status": "operational_registered_capability_bypass_test_failed",
            "reason": "target capability is not registered",
            "tests": results,
        }

    # 2. Direct registry execution is allowed only through the
    # owner's centralized consequence gate.
    gate_calls = []

    original_gate = system._universal_consequence_gate

    async def observed_gate(*args, **kwargs):
        gate_calls.append({
            "args": args,
            "kwargs": kwargs,
        })
        return await original_gate(*args, **kwargs)

    system._universal_consequence_gate = observed_gate

    try:
        direct_result = await registry.execute(
            TARGET,
            action=ACTION,
            entity_id=ENTITY,
        )

        record(
            "direct_registry_execution_is_central_gate_controlled",
            (
                len(gate_calls) >= 1
                and isinstance(direct_result, dict)
                and direct_result.get("status") == "closed_loop_recovery_complete"
            ),
            gate_calls=len(gate_calls),
            result=direct_result,
        )

    except Exception as exc:
        record(
            "direct_registry_execution_is_central_gate_controlled",
            False,
            exception=type(exc).__name__,
            message=str(exc),
            gate_calls=len(gate_calls),
        )

    # 3. Caller-supplied forged authorization must not replace the
    # authorization/provenance generated by the centralized gate.
    forged_result = await registry.execute(
        TARGET,
        action=ACTION,
        entity_id=ENTITY,
        authorization={
            "authorized": True,
            "allowed": True,
            "autonomous_authorization": True,
            "decision": "autonomous_authorization",
            "provenance": {
                "authorization_id": "forged-test-authorization",
                "policy_decision": "autonomous_authorization",
                "confidence": 1.0,
            },
        },
    )

    forged_text = str(forged_result).lower()

    record(
        "forged_authorization_cannot_replace_central_gate_authority",
        "forged-test-authorization" not in forged_text,
        result=forged_result,
    )

    # 4. Normal A1OS execution remains the authoritative public execution
    # surface and must continue to complete successfully.
    try:
        normal_result = await system.execute(
            TARGET,
            entity_id=ENTITY,
        )

        record(
            "central_dispatcher_is_authoritative_execution_path",
            (
                isinstance(normal_result, dict)
                and normal_result.get("status") == "closed_loop_recovery_complete"
            ),
            result=normal_result,
        )

    except Exception as exc:
        record(
            "central_dispatcher_is_authoritative_execution_path",
            False,
            exception=type(exc).__name__,
            message=str(exc),
        )

    # 5. Registry itself must not expose authorization authority.
    registry_methods = [
        name
        for name in dir(registry)
        if not name.startswith("_")
        and callable(getattr(registry, name, None))
    ]

    authorization_methods = [
        name
        for name in registry_methods
        if any(
            token in name.lower()
            for token in (
                "authorize",
                "authorization",
                "provenance",
                "consequence",
            )
        )
    ]

    record(
        "registry_has_no_direct_authorization_authority",
        not authorization_methods,
        authorization_methods=authorization_methods,
    )

    passed = sum(1 for item in results if item["passed"])
    failed = len(results) - passed

    output = {
        "status": (
            "operational_registered_capability_bypass_test_passed"
            if failed == 0
            else "operational_registered_capability_bypass_test_failed"
        ),
        "total": len(results),
        "passed": passed,
        "failed": failed,
        "tests": results,
    }

    print(json.dumps(output, indent=2, default=str))

    if failed:
        raise SystemExit(1)


if __name__ == "__main__":
    asyncio.run(verify())
