import React from "react";
import {a1osApi} from "./api/client";
const api=async(path,opt={})=>{const r=await fetch(path,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}});if(!r.ok)throw Error(await r.text());return r.json()};
const modules=["Dashboard","Clients","Projects","Quotes","Invoices","Payments","Tasks","Documents","Reports","Settings"];
function Crud({title,rows,fields,endpoint,reload}){const [form,setForm]=React.useState({});const save=async()=>{await api(endpoint,{method:"POST",body:JSON.stringify(form)});setForm({});reload()};return <section><div className="pageHead"><h1>{title}</h1></div><div className="card form">{fields.map(f=><input key={f} placeholder={f} value={form[f]||""} onChange={e=>setForm({...form,[f]:e.target.value})}/>)}<button onClick={save}>Create</button></div><div className="card"><table><thead><tr>{Object.keys(rows[0]||Object.fromEntries(fields.map(x=>[x,""]))).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{Object.keys(r).map(k=><td key={k}>{String(r[k]??"")}</td>)}</tr>)}</tbody></table>{!rows.length&&<p>No records.</p>}</div></section>}
function App(){const [page,setPage]=React.useState("Dashboard");const [data,setData]=React.useState([]);const [report,setReport]=React.useState(null);const [loading,setLoading]=React.useState(false);
const load=React.useCallback(async()=>{setLoading(true);try{let x=[];if(page==="Clients")x=(await a1osApi.clients.list()).clients||[];else if(page==="Projects")x=(await a1osApi.projects?.list?.())?.projects||[];else if(page==="Quotes")x=(await a1osApi.quotes.list()).quotes||[];else if(page==="Invoices")x=(await a1osApi.invoices.list()).invoices||[];else if(page==="Payments")x=(await api("/v1/professional-services/payments")).payments||[];else if(page==="Tasks")x=(await api("/v1/professional-services/tasks")).tasks||[];else if(page==="Documents")x=(await api("/v1/professional-services/documents")).documents||[];else if(page==="Reports")report&&0;setData(x)}finally{setLoading(false)}},[page]);
React.useEffect(()=>{load()},[load]);React.useEffect(()=>{if(page==="Reports")Promise.all([api("/v1/professional-services/reports/financial"),api("/v1/professional-services/reports/receivables")]).then(([f,r])=>setReport({...f,...r}))},[page]);
const fields={Payments:["invoice_id","amount","payment_method","reference"],Tasks:["title","description","status","priority","due_date"],Documents:["name","document_type","storage_path"]};
return <div className="app"><aside><h2>A1OS</h2><small>Professional Services</small>{modules.map(m=><button className={page===m?"active":""} onClick={()=>setPage(m)} key={m}>{m}</button>)}</aside><main><header><strong>{page}</strong><span>Production</span></header>{page==="Dashboard"?<section><h1>Professional Services</h1><div className="grid">{["Clients","Projects","Quotes","Invoices","Payments","Tasks"].map(x=><button className="card tile" onClick={()=>setPage(x)} key={x}><b>{x}</b><span>Open workspace</span></button>)}</div></section>:page==="Reports"?<section><h1>Reports</h1><div className="grid">{report&&["invoiced","paid","outstanding"].map(k=><div className="card tile" key={k}><b>UGX {Number(report[k]||0).toLocaleString()}</b><span>{k}</span></div>)}</div><div className="card"><h3>Receivables</h3><pre>{JSON.stringify(report?.receivables||[],null,2)}</pre></div></section>:page==="Settings"?<Settings/>:fields[page]?<Crud title={page} rows={data} fields={fields[page]} endpoint={"/v1/professional-services/"+page.toLowerCase()} reload={load}/>:<Crud title={page} rows={data} fields={page==="Clients"?["name","email","phone","company"]:page==="Invoices"?["title","amount","due_date"]:["title","amount"]} endpoint="" reload={load}/>} {loading&&<div>Loading…</div>}</main></div>}
function Settings(){const [key,setKey]=React.useState("");const [value,setValue]=React.useState("");return <section><h1>Settings</h1><div className="card form"><input placeholder="Setting key" value={key} onChange={e=>setKey(e.target.value)}/><input placeholder="Value" value={value} onChange={e=>setValue(e.target.value)}/><button onClick={()=>api("/v1/professional-services/settings",{method:"PUT",body:JSON.stringify({key,value})})}>Save</button></div></section>}
export { App };
