"""Lightweight customized vertical generator."""
from __future__ import annotations
import json
import re
import shutil
import sys
from pathlib import Path
from tools.a1os_factory.engine_runtime import EngineSpec, FactoryEngine

SLUG = re.compile(r"^[a-z][a-z0-9-]{1,62}$")

def generate(name: str, requirements: dict, root: Path = Path("products")) -> Path:
    if not SLUG.fullmatch(name):
        raise ValueError("product name must be a lowercase slug")
    target = root / name
    if target.exists():
        raise FileExistsError(f"product already exists: {target}")
    target.mkdir(parents=True)
    for folder in ("config", "pages", "components", "workflows", "forms", "integrations", "state", "assets", "tests"):
        (target / folder).mkdir()
    manifest = {
        "name": name,
        "type": "frontend-vertical",
        "status": "generated",
        "backend": "a1os-platform-api",
        "customized": True,
        "requirements": requirements,
        "platform_owned": ["auth", "tenancy", "authorization", "rbac", "persistence", "deployment"],
        "vertical_owned": ["pages", "components", "workflows", "forms", "integrations", "state", "assets", "tests"],
    }
    (target / "A1OS_VERTICAL.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (target / "README.md").write_text(f"# {name}\n\nGenerated by the lightweight A1OS Product Factory.\n", encoding="utf-8")
    (target / "tests" / "factory_manifest_test.py").write_text(
        "import json\nfrom pathlib import Path\n\ndef test_manifest():\n    data=json.loads(Path(__file__).parents[1].joinpath('A1OS_VERTICAL.json').read_text())\n    assert data['customized'] is True\n", encoding="utf-8")
    return target

ENGINE = FactoryEngine(EngineSpec("vertical-generator", "vertical-generator", "vertical-manifest"))

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python3 vertical_os_generator_engine.py PRODUCT REQUIREMENTS_JSON")
        raise SystemExit(2)
    req = json.loads(Path(sys.argv[2]).read_text(encoding="utf-8"))
    print(generate(sys.argv[1], req))
