-- Canonical production schema is applied to the A1OS Supabase project by migration:
-- legal_security_hardening
-- The repository keeps the vertical contract here; deployment migrations are tracked in Supabase.
