- name: Configure build-a-harmless-test-capability
  hosts: all
  gather_facts: true
  tasks:
    - name: Report product
      ansible.builtin.debug:
        msg: "Configuring build-a-harmless-test-capability"
