import React,{useEffect,useMemo,useState}from"react";
import{supabase}from"./lib/supabase.js";
const nav=["Command Center","Matters","Clients","Diary","Documents","Billing","Research","Audit"];
const areas=["Litigation","Commercial","Labour","Conveyancing","Advisory"];
export function App(){
 const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[active,setActive]=useState("Command Center"),[matters,setMatters]=useState([]),[clients,setClients]=useState([]),[deadlines,setDeadlines]=useState([]),[tasks,setTasks]=useState([]),[documents,setDocuments]=useState([]),[invoices,setInvoices]=useState([]),[research,setResearch]=useState([]),[audit,setAudit]=useState([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[showNew,setShowNew]=useState(false),[showClient,setShowClient]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load();else setLoading(false)},[session]);
 async function load(){setLoading(true);setError("");
  const results=await Promise.all([
   supabase.schema("legal").from("matters").select("id,matter_number,title,practice_area,status,opened_at,client_id,legal_clients(legal_name)").order("created_at",{ascending:false}),
   supabase.schema("legal").from("clients").select("id,client_number,legal_name,client_type,status,phone,email").order("created_at",{ascending:false}),
   supabase.schema("legal").from("deadlines").select("id,matter_id,title,deadline_at,status,source").eq("status","open").order("deadline_at"),
   supabase.schema("legal").from("tasks").select("id,matter_id,title,status,priority,due_at").neq("status","completed").order("due_at"),
   supabase.schema("legal").from("documents").select("id,matter_id,title,document_type,version,created_at").order("created_at",{ascending:false}),
   supabase.schema("legal").from("invoices").select("id,matter_id,invoice_number,amount,currency,status,due_date").order("created_at",{ascending:false}),
   supabase.schema("legal").from("research").select("id,matter_id,title,source,citation,url,created_at").order("created_at",{ascending:false}),
   supabase.schema("legal").from("audit_events").select("id,actor_id,matter_id,action,entity_type,created_at").order("created_at",{ascending:false}).limit(50),
   supabase.from("legal_profiles").select("full_name,role,active").eq("user_id",session.user.id).maybeSingle()
  ]);
  const bad=results.find(x=>x.error);if(bad){setError(bad.error.message);setLoading(false);return}
  const[d1,d2,d3,d4,d5,d6,d7,d8,d9]=results;setMatters(d1.data||[]);setClients(d2.data||[]);setDeadlines(d3.data||[]);setTasks(d4.data||[]);setDocuments(d5.data||[]);setInvoices(d6.data||[]);setResearch(d7.data||[]);setAudit(d8.data||[]);setProfile(d9.data);setLoading(false);
 }
 async function signIn(e){e.preventDefault();setError("");const f=new FormData(e.currentTarget),r=await supabase.auth.signInWithPassword({email:f.get("email"),password:f.get("password")});if(r.error)setError(r.error.message)}
 async function signOut(){await supabase.auth.signOut();setSession(null)}
 async function createMatter(e){e.preventDefault();setError("");const f=new FormData(e.currentTarget),r=await supabase.schema("legal").from("matters").insert({matter_number:f.get("matter_number"),title:f.get("title"),practice_area:f.get("practice_area"),matter_type:f.get("matter_type"),status:"intake",client_id:f.get("client_id"),description:f.get("description"),created_by:session.user.id}).select("id").single();if(r.error){setError(r.error.message);return}await supabase.schema("legal").from("audit_events").insert({actor_id:session.user.id,matter_id:r.data.id,action:"matter_created",entity_type:"matters",entity_id:r.data.id});setShowNew(false);await load()}
 async function createClient(e){e.preventDefault();setError("");const f=new FormData(e.currentTarget),r=await supabase.schema("legal").from("clients").insert({client_number:f.get("client_number")||`BB-C-${Date.now()}`,legal_name:f.get("legal_name"),client_type:f.get("client_type"),phone:f.get("phone")||null,email:f.get("email")||null,address:f.get("address")||null,status:"active",created_by:session.user.id});if(r.error){setError(r.error.message);return}setShowClient(false);await load()}
 const filtered=useMemo(()=>matters.filter(m=>Object.values(m).join(" ").toLowerCase().includes(query.toLowerCase())),[matters,query]);
 if(!session)return <Login error={error} onSubmit={signIn}/>;
 if(loading)return <div className="loading">Loading governed practice data…</div>;
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="mark">BB</div><div><strong>Barya, Byamugisha</strong><span>& Co. Advocates</span></div></div><div className="workspace">INTERNAL PRACTICE PLATFORM</div><nav>{nav.map(n=><button key={n} className={active===n?"active":""} onClick={()=>setActive(n)}>{n}</button>)}</nav><div className="security">🔒 Matter-level confidentiality<small>A1OS governed · {profile?.role||"staff"}</small></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow">BARYA, BYAMUGISHA & CO.</span><h1>{active}</h1></div><div className="top-actions"><span className="user">{profile?.full_name||session.user.email} · {profile?.role||"staff"}</span><button onClick={signOut}>Sign out</button>{["partner","administrator"].includes(profile?.role)&&<><button onClick={()=>setShowClient(true)}>+ Client</button><button className="primary" onClick={()=>setShowNew(true)}>+ New matter</button></>}</div></header>{error&&<div className="error-banner">{error}</div>}<Workspace active={active} matters={filtered} clients={clients} deadlines={deadlines} tasks={tasks} documents={documents} invoices={invoices} research={research} audit={audit} query={query} setQuery={setQuery}/>{showNew&&<MatterModal clients={clients} onClose={()=>setShowNew(false)} onSubmit={createMatter}/>} {showClient&&<ClientModal onClose={()=>setShowClient(false)} onSubmit={createClient}/>}</main></div>
}
function Login({error,onSubmit}){return <div className="login"><div className="login-card"><div className="mark">BB</div><span className="eyebrow">BARYA, BYAMUGISHA & CO.</span><h1>Internal Practice Platform</h1><p>Secure access to firm matters, clients, deadlines and work product.</p><form onSubmit={onSubmit}><label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label>{error&&<div className="error-banner">{error}</div>}<button className="primary full">Sign in</button></form></div></div>}
function Workspace(p){const{active,matters,clients,deadlines,tasks,documents,invoices,research,audit,query,setQuery}=p;if(active==="Command Center")return <section><div className="hero"><div><span className="eyebrow">PRACTICE OVERVIEW</span><h2>Know what needs attention.</h2><p>One governed workspace for matters, deadlines, documents, billing and legal work.</p></div><div className="hero-status"><strong>Protected</strong><span>Role + matter access</span></div></div><div className="metrics"><Metric label="Visible matters" value={matters.length}/><Metric label="Clients" value={clients.length}/><Metric label="Open deadlines" value={deadlines.length}/><Metric label="Open tasks" value={tasks.length}/></div><Panel title="Recent matters"><Tools value={query} setValue={setQuery}/><MatterTable matters={matters}/></Panel></section>;
if(active==="Matters")return <section><Panel title="Matter register"><Tools value={query} setValue={setQuery}/><MatterTable matters={matters}/></Panel></section>;
if(active==="Clients")return <section><Panel title="Client register"><SimpleTable rows={clients} cols={[["legal_name","Client"],["client_type","Type"],["status","Status"],["phone","Phone"],["email","Email"]]}/></Panel></section>;
if(active==="Diary")return <section><Panel title="Open deadlines"><SimpleTable rows={deadlines} cols={[["title","Deadline"],["deadline_at","Due"],["status","Status"],["source","Source"]]}/><h3 className="subhead">Open tasks</h3><SimpleTable rows={tasks} cols={[["title","Task"],["priority","Priority"],["status","Status"],["due_at","Due"]]}/></Panel></section>;
if(active==="Documents")return <section><Panel title="Document register"><SimpleTable rows={documents} cols={[["title","Document"],["document_type","Type"],["version","Version"],["created_at","Created"]]}/></Panel></section>;
if(active==="Billing")return <section><Panel title="Invoices"><SimpleTable rows={invoices} cols={[["invoice_number","Invoice"],["amount","Amount"],["currency","Currency"],["status","Status"],["due_date","Due"]]}/></Panel></section>;
if(active==="Research")return <section><Panel title="Research register"><SimpleTable rows={research} cols={[["title","Research"],["source","Source"],["citation","Citation"],["created_at","Created"]]}/></Panel></section>;
return <section><Panel title="Audit trail"><SimpleTable rows={audit} cols={[["action","Action"],["entity_type","Entity"],["actor_id","Actor"],["created_at","Time"]]}/></Panel></section>}
function Tools({value,setValue}){return <div className="panel-tools"><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Search matters…"/></div>}
function Panel({title,children}){return <div className="panel"><div className="panel-head"><div><span className="eyebrow">GOVERNED WORKSPACE</span><h3>{title}</h3></div></div>{children}</div>}
function Metric({label,value}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function MatterTable({matters}){return <SimpleTable rows={matters} cols={[["title","Matter"],["client","Client"],["practice_area","Area"],["status","Status"],["opened_at","Opened"]]} render={(m,k)=>k==="client"?m.clients?.legal_name||"—":m[k]??"—"}/>}
function SimpleTable({rows,cols,render}){return <div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c[0]}>{render?render(r,c[0]):(r[c[0]]??"—")}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty-state">No records available.</div>}</div>}
function MatterModal({clients,onClose,onSubmit}){return <Modal title="Open a new matter" onClose={onClose} onSubmit={onSubmit}><label>Matter number<input name="matter_number" required placeholder="BB-2026-001"/></label><label>Matter title<input name="title" required/></label><label>Client<select name="client_id" required><option value="">Select client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.legal_name}</option>)}</select></label><label>Practice area<select name="practice_area">{areas.map(a=><option key={a}>{a}</option>)}</select></label><label>Matter type<input name="matter_type"/></label><label>Description<textarea name="description" rows="3"/></label><button className="primary full">Create matter</button></Modal>}
function ClientModal({onClose,onSubmit}){return <Modal title="Add client" onClose={onClose} onSubmit={onSubmit}><label>Client number<input name="client_number" placeholder="BB-C-001"/></label><label>Legal name<input name="legal_name" required/></label><label>Type<select name="client_type"><option>individual</option><option>company</option><option>partnership</option><option>institution</option><option>other</option></select></label><label>Phone<input name="phone"/></label><label>Email<input name="email" type="email"/></label><label>Address<textarea name="address" rows="2"/></label><button className="primary full">Create client</button></Modal>}
function Modal({title,onClose,onSubmit,children}){return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><div className="panel-head"><div><span className="eyebrow">GOVERNED INTAKE</span><h3>{title}</h3></div><button type="button" onClick={onClose}>×</button></div>{children}</form></div>}
