-- Legal vertical security migration applied to Supabase project prqbeocaycxqsremxvmb
alter table public.legal_profiles enable row level security;
alter table public.legal_clients enable row level security;
alter table public.legal_matters enable row level security;
alter table public.legal_matter_members enable row level security;
alter table public.legal_deadlines enable row level security;
alter table public.legal_documents enable row level security;
alter table public.legal_evidence enable row level security;
alter table public.legal_tasks enable row level security;
alter table public.legal_invoices enable row level security;
alter table public.legal_payments enable row level security;
alter table public.legal_research enable row level security;
alter table public.legal_audit_events enable row level security;

create or replace function public.legal_is_privileged() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.legal_profiles p where p.user_id=auth.uid() and p.active and p.role in ('partner','administrator')); $$;
create or replace function public.legal_has_matter_access(target_matter uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.legal_is_privileged() or exists(select 1 from public.legal_matters m where m.id=target_matter and m.created_by=auth.uid()) or exists(select 1 from public.legal_matter_members mm where mm.matter_id=target_matter and mm.user_id=auth.uid()); $$;
create or replace function public.legal_is_finance() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.legal_profiles p where p.user_id=auth.uid() and p.active and p.role in ('partner','administrator','finance')); $$;

drop policy if exists legal_profiles_select on public.legal_profiles;
create policy legal_profiles_select on public.legal_profiles for select to authenticated using (user_id=auth.uid() or public.legal_is_privileged());
drop policy if exists legal_clients_select on public.legal_clients;
create policy legal_clients_select on public.legal_clients for select to authenticated using (exists(select 1 from public.legal_profiles p where p.user_id=auth.uid() and p.active));
drop policy if exists legal_clients_write on public.legal_clients;
create policy legal_clients_write on public.legal_clients for all to authenticated using (public.legal_is_privileged()) with check (public.legal_is_privileged());
drop policy if exists legal_matters_select on public.legal_matters;
create policy legal_matters_select on public.legal_matters for select to authenticated using (public.legal_has_matter_access(id));
drop policy if exists legal_matters_insert on public.legal_matters;
create policy legal_matters_insert on public.legal_matters for insert to authenticated with check (exists(select 1 from public.legal_profiles p where p.user_id=auth.uid() and p.active and p.role in ('partner','administrator','advocate')) and created_by=auth.uid());
drop policy if exists legal_matters_update on public.legal_matters;
create policy legal_matters_update on public.legal_matters for update to authenticated using (public.legal_has_matter_access(id)) with check (public.legal_has_matter_access(id));
drop policy if exists legal_members_select on public.legal_matter_members;
create policy legal_members_select on public.legal_matter_members for select to authenticated using (public.legal_has_matter_access(matter_id));
drop policy if exists legal_members_manage on public.legal_matter_members;
create policy legal_members_manage on public.legal_matter_members for all to authenticated using (public.legal_is_privileged()) with check (public.legal_is_privileged());
drop policy if exists legal_deadlines_access on public.legal_deadlines;
create policy legal_deadlines_access on public.legal_deadlines for all to authenticated using (public.legal_has_matter_access(matter_id)) with check (public.legal_has_matter_access(matter_id));
drop policy if exists legal_documents_access on public.legal_documents;
create policy legal_documents_access on public.legal_documents for all to authenticated using (public.legal_has_matter_access(matter_id)) with check (public.legal_has_matter_access(matter_id));
drop policy if exists legal_evidence_access on public.legal_evidence;
create policy legal_evidence_access on public.legal_evidence for all to authenticated using (public.legal_has_matter_access(matter_id)) with check (public.legal_has_matter_access(matter_id));
drop policy if exists legal_tasks_access on public.legal_tasks;
create policy legal_tasks_access on public.legal_tasks for all to authenticated using (matter_id is null or public.legal_has_matter_access(matter_id)) with check (matter_id is null or public.legal_has_matter_access(matter_id));
drop policy if exists legal_invoices_access on public.legal_invoices;
create policy legal_invoices_access on public.legal_invoices for select to authenticated using (public.legal_is_finance() or public.legal_has_matter_access(matter_id));
drop policy if exists legal_invoices_write on public.legal_invoices;
create policy legal_invoices_write on public.legal_invoices for all to authenticated using (public.legal_is_finance()) with check (public.legal_is_finance());
drop policy if exists legal_payments_access on public.legal_payments;
create policy legal_payments_access on public.legal_payments for all to authenticated using (public.legal_is_finance() or exists(select 1 from public.legal_invoices i where i.id=invoice_id and public.legal_has_matter_access(i.matter_id))) with check (public.legal_is_finance() or exists(select 1 from public.legal_invoices i where i.id=invoice_id and public.legal_has_matter_access(i.matter_id)));
drop policy if exists legal_research_access on public.legal_research;
create policy legal_research_access on public.legal_research for all to authenticated using (matter_id is null or public.legal_has_matter_access(matter_id)) with check (matter_id is null or public.legal_has_matter_access(matter_id));
drop policy if exists legal_audit_select on public.legal_audit_events;
create policy legal_audit_select on public.legal_audit_events for select to authenticated using (public.legal_is_privileged());
drop policy if exists legal_audit_insert on public.legal_audit_events;
create policy legal_audit_insert on public.legal_audit_events for insert to authenticated with check (actor_id=auth.uid() and (matter_id is null or public.legal_has_matter_access(matter_id)));

revoke all on public.legal_profiles,public.legal_clients,public.legal_matters,public.legal_matter_members,public.legal_deadlines,public.legal_documents,public.legal_evidence,public.legal_tasks,public.legal_invoices,public.legal_payments,public.legal_research,public.legal_audit_events from anon;
grant select,insert,update,delete on public.legal_profiles,public.legal_clients,public.legal_matters,public.legal_matter_members,public.legal_deadlines,public.legal_documents,public.legal_evidence,public.legal_tasks,public.legal_invoices,public.legal_payments,public.legal_research,public.legal_audit_events to authenticated;
revoke execute on function public.legal_has_matter_access(uuid) from public,anon,authenticated;
revoke execute on function public.legal_is_finance() from public,anon,authenticated;
revoke execute on function public.legal_is_privileged() from public,anon,authenticated;