apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-control-plane-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2e-control-plane-test
  template:
    metadata:
      labels:
        app: e2e-control-plane-test
    spec:
      containers:
        - name: e2e-control-plane-test
          image: e2e-control-plane-test:latest
          imagePullPolicy: IfNotPresent
